apiVersion: costmanagement-metrics-cfg.openshift.io/v1beta1
kind: CostManagementMetricsConfig
metadata:
  name: costmanagementmetricscfg-sample-v1beta1
spec:
  api_url: https://cloud.redhat.com
  authentication:
    secret_name: operator-service-account
    token_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    type: service-account
  packaging:
    max_reports_to_store: 30
    max_size_MB: 100
  prometheus_config:
    collect_previous_data: true
    context_timeout: 120
    disable_metrics_collection_cost_management: false
    disable_metrics_collection_resource_optimization: false
    service_address: https://thanos-querier.openshift-monitoring.svc:9091
    skip_tls_verification: false
  source:
    check_cycle: 1440
    create_source: true
    name: demolab
    sources_path: /api/sources/v1.0/
  upload:
    ingress_path: /api/ingress/v1/upload
    upload_cycle: 360
    upload_toggle: true
    upload_wait: 0
    validate_cert: true
