
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: costmanagement-metrics-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
