---

kind: Secret
apiVersion: v1
metadata:
  name: dev-auth-secret
  namespace: costmanagement-metrics-operator
data:
  username: >-
    Y2xvdWQucmVkaGF0LmNvbSB1c2VybmFtZQ==
  password: >-
    Y2xvdWQucmVkaGF0LmNvbSBwYXNzd29yZA==
