# permissions for end users to view kokumetricsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kokumetricscfg-viewer-role
rules:
- apiGroups:
  - koku-metrics-cfg.openshift.io
  resources:
  - kokumetricsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - koku-metrics-cfg.openshift.io
  resources:
  - kokumetricsconfigs/status
  verbs:
  - get
