# permissions for end users to edit kokumetricsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kokumetricsconfig-editor-role
rules:
- apiGroups:
  - koku-metrics-cfg.openshift.io
  resources:
  - kokumetricsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - koku-metrics-cfg.openshift.io
  resources:
  - kokumetricsconfigs/status
  verbs:
  - get
