apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-config-rolebinding
  namespace: openshift-config
roleRef:
  kind: Role
  name: manager-config-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-cost

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-config-rolebinding
  namespace: openshift-cost
roleRef:
  kind: Role
  name: manager-config-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-cost