apiVersion: koku-metrics-cfg.openshift.io/v1beta1
kind: KokuMetricsConfig
metadata:
  name: kokumetricscfg-sample-air-gapped
spec:
  authentication: {}
  packaging:
    max_reports_to_store: 30
    max_size_MB: 100
  prometheus_config: {}
  source: {}
  upload:
    upload_cycle: 360
    upload_toggle: false
