
---

    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: openshift-cost
      name: trusted-ca-bundle
      annotations:
        release.openshift.io/create-only: "true"
      labels:
        config.openshift.io/inject-trusted-cabundle: "true"
