// +build !ignore_autogenerated

/*


Copyright 2021 Red Hat, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha2 "github.com/project-koku/koku-metrics-operator/api/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuthenticationSpec)(nil), (*v1alpha2.AuthenticationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec(a.(*AuthenticationSpec), b.(*v1alpha2.AuthenticationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AuthenticationSpec)(nil), (*AuthenticationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec(a.(*v1alpha2.AuthenticationSpec), b.(*AuthenticationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuthenticationStatus)(nil), (*v1alpha2.AuthenticationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus(a.(*AuthenticationStatus), b.(*v1alpha2.AuthenticationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AuthenticationStatus)(nil), (*AuthenticationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus(a.(*v1alpha2.AuthenticationStatus), b.(*AuthenticationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudDotRedHatSourceSpec)(nil), (*v1alpha2.CloudDotRedHatSourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec(a.(*CloudDotRedHatSourceSpec), b.(*v1alpha2.CloudDotRedHatSourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CloudDotRedHatSourceSpec)(nil), (*CloudDotRedHatSourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec(a.(*v1alpha2.CloudDotRedHatSourceSpec), b.(*CloudDotRedHatSourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudDotRedHatSourceStatus)(nil), (*v1alpha2.CloudDotRedHatSourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus(a.(*CloudDotRedHatSourceStatus), b.(*v1alpha2.CloudDotRedHatSourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CloudDotRedHatSourceStatus)(nil), (*CloudDotRedHatSourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus(a.(*v1alpha2.CloudDotRedHatSourceStatus), b.(*CloudDotRedHatSourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EmbeddedObjectMetadata)(nil), (*v1alpha2.EmbeddedObjectMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata(a.(*EmbeddedObjectMetadata), b.(*v1alpha2.EmbeddedObjectMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.EmbeddedObjectMetadata)(nil), (*EmbeddedObjectMetadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata(a.(*v1alpha2.EmbeddedObjectMetadata), b.(*EmbeddedObjectMetadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EmbeddedPersistentVolumeClaim)(nil), (*v1alpha2.EmbeddedPersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(a.(*EmbeddedPersistentVolumeClaim), b.(*v1alpha2.EmbeddedPersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.EmbeddedPersistentVolumeClaim)(nil), (*EmbeddedPersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(a.(*v1alpha2.EmbeddedPersistentVolumeClaim), b.(*EmbeddedPersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KokuMetricsConfig)(nil), (*v1alpha2.KokuMetricsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig(a.(*KokuMetricsConfig), b.(*v1alpha2.KokuMetricsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.KokuMetricsConfig)(nil), (*KokuMetricsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig(a.(*v1alpha2.KokuMetricsConfig), b.(*KokuMetricsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KokuMetricsConfigList)(nil), (*v1alpha2.KokuMetricsConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KokuMetricsConfigList_To_v1alpha2_KokuMetricsConfigList(a.(*KokuMetricsConfigList), b.(*v1alpha2.KokuMetricsConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.KokuMetricsConfigList)(nil), (*KokuMetricsConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_KokuMetricsConfigList_To_v1alpha1_KokuMetricsConfigList(a.(*v1alpha2.KokuMetricsConfigList), b.(*KokuMetricsConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KokuMetricsConfigSpec)(nil), (*v1alpha2.KokuMetricsConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec(a.(*KokuMetricsConfigSpec), b.(*v1alpha2.KokuMetricsConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.KokuMetricsConfigSpec)(nil), (*KokuMetricsConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_KokuMetricsConfigSpec_To_v1alpha1_KokuMetricsConfigSpec(a.(*v1alpha2.KokuMetricsConfigSpec), b.(*KokuMetricsConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KokuMetricsConfigStatus)(nil), (*v1alpha2.KokuMetricsConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus(a.(*KokuMetricsConfigStatus), b.(*v1alpha2.KokuMetricsConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.KokuMetricsConfigStatus)(nil), (*KokuMetricsConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_KokuMetricsConfigStatus_To_v1alpha1_KokuMetricsConfigStatus(a.(*v1alpha2.KokuMetricsConfigStatus), b.(*KokuMetricsConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackagingSpec)(nil), (*v1alpha2.PackagingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec(a.(*PackagingSpec), b.(*v1alpha2.PackagingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PackagingSpec)(nil), (*PackagingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec(a.(*v1alpha2.PackagingSpec), b.(*PackagingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackagingStatus)(nil), (*v1alpha2.PackagingStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus(a.(*PackagingStatus), b.(*v1alpha2.PackagingStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PackagingStatus)(nil), (*PackagingStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus(a.(*v1alpha2.PackagingStatus), b.(*PackagingStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PrometheusSpec)(nil), (*v1alpha2.PrometheusSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec(a.(*PrometheusSpec), b.(*v1alpha2.PrometheusSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PrometheusSpec)(nil), (*PrometheusSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec(a.(*v1alpha2.PrometheusSpec), b.(*PrometheusSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PrometheusStatus)(nil), (*v1alpha2.PrometheusStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus(a.(*PrometheusStatus), b.(*v1alpha2.PrometheusStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PrometheusStatus)(nil), (*PrometheusStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus(a.(*v1alpha2.PrometheusStatus), b.(*PrometheusStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReportsStatus)(nil), (*v1alpha2.ReportsStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus(a.(*ReportsStatus), b.(*v1alpha2.ReportsStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ReportsStatus)(nil), (*ReportsStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus(a.(*v1alpha2.ReportsStatus), b.(*ReportsStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageStatus)(nil), (*v1alpha2.StorageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus(a.(*StorageStatus), b.(*v1alpha2.StorageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.StorageStatus)(nil), (*StorageStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus(a.(*v1alpha2.StorageStatus), b.(*StorageStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UploadSpec)(nil), (*v1alpha2.UploadSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UploadSpec_To_v1alpha2_UploadSpec(a.(*UploadSpec), b.(*v1alpha2.UploadSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.UploadSpec)(nil), (*UploadSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec(a.(*v1alpha2.UploadSpec), b.(*UploadSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UploadStatus)(nil), (*v1alpha2.UploadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UploadStatus_To_v1alpha2_UploadStatus(a.(*UploadStatus), b.(*v1alpha2.UploadStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.UploadStatus)(nil), (*UploadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus(a.(*v1alpha2.UploadStatus), b.(*UploadStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec(in *AuthenticationSpec, out *v1alpha2.AuthenticationSpec, s conversion.Scope) error {
	out.AuthType = v1alpha2.AuthenticationType(in.AuthType)
	out.AuthenticationSecretName = in.AuthenticationSecretName
	return nil
}

// Convert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec(in *AuthenticationSpec, out *v1alpha2.AuthenticationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec(in, out, s)
}

func autoConvert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec(in *v1alpha2.AuthenticationSpec, out *AuthenticationSpec, s conversion.Scope) error {
	out.AuthType = AuthenticationType(in.AuthType)
	out.AuthenticationSecretName = in.AuthenticationSecretName
	return nil
}

// Convert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec is an autogenerated conversion function.
func Convert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec(in *v1alpha2.AuthenticationSpec, out *AuthenticationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec(in, out, s)
}

func autoConvert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus(in *AuthenticationStatus, out *v1alpha2.AuthenticationStatus, s conversion.Scope) error {
	out.AuthType = v1alpha2.AuthenticationType(in.AuthType)
	out.AuthenticationSecretName = in.AuthenticationSecretName
	out.AuthenticationCredentialsFound = in.AuthenticationCredentialsFound
	return nil
}

// Convert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus(in *AuthenticationStatus, out *v1alpha2.AuthenticationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus(in, out, s)
}

func autoConvert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus(in *v1alpha2.AuthenticationStatus, out *AuthenticationStatus, s conversion.Scope) error {
	out.AuthType = AuthenticationType(in.AuthType)
	out.AuthenticationSecretName = in.AuthenticationSecretName
	out.AuthenticationCredentialsFound = in.AuthenticationCredentialsFound
	return nil
}

// Convert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus is an autogenerated conversion function.
func Convert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus(in *v1alpha2.AuthenticationStatus, out *AuthenticationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus(in, out, s)
}

func autoConvert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec(in *CloudDotRedHatSourceSpec, out *v1alpha2.CloudDotRedHatSourceSpec, s conversion.Scope) error {
	out.SourcesAPIPath = in.SourcesAPIPath
	out.SourceName = in.SourceName
	out.CreateSource = in.CreateSource
	out.CheckCycle = in.CheckCycle
	return nil
}

// Convert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec(in *CloudDotRedHatSourceSpec, out *v1alpha2.CloudDotRedHatSourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec(in, out, s)
}

func autoConvert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec(in *v1alpha2.CloudDotRedHatSourceSpec, out *CloudDotRedHatSourceSpec, s conversion.Scope) error {
	out.SourcesAPIPath = in.SourcesAPIPath
	out.SourceName = in.SourceName
	out.CreateSource = in.CreateSource
	out.CheckCycle = in.CheckCycle
	return nil
}

// Convert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec is an autogenerated conversion function.
func Convert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec(in *v1alpha2.CloudDotRedHatSourceSpec, out *CloudDotRedHatSourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec(in, out, s)
}

func autoConvert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus(in *CloudDotRedHatSourceStatus, out *v1alpha2.CloudDotRedHatSourceStatus, s conversion.Scope) error {
	out.SourcesAPIPath = in.SourcesAPIPath
	out.SourceName = in.SourceName
	out.SourceDefined = in.SourceDefined
	out.CreateSource = in.CreateSource
	out.SourceError = in.SourceError
	out.LastSourceCheckTime = in.LastSourceCheckTime
	out.CheckCycle = in.CheckCycle
	return nil
}

// Convert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus(in *CloudDotRedHatSourceStatus, out *v1alpha2.CloudDotRedHatSourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus(in, out, s)
}

func autoConvert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus(in *v1alpha2.CloudDotRedHatSourceStatus, out *CloudDotRedHatSourceStatus, s conversion.Scope) error {
	out.SourcesAPIPath = in.SourcesAPIPath
	out.SourceName = in.SourceName
	out.SourceDefined = in.SourceDefined
	out.CreateSource = in.CreateSource
	out.SourceError = in.SourceError
	out.LastSourceCheckTime = in.LastSourceCheckTime
	out.CheckCycle = in.CheckCycle
	return nil
}

// Convert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus is an autogenerated conversion function.
func Convert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus(in *v1alpha2.CloudDotRedHatSourceStatus, out *CloudDotRedHatSourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus(in, out, s)
}

func autoConvert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata(in *EmbeddedObjectMetadata, out *v1alpha2.EmbeddedObjectMetadata, s conversion.Scope) error {
	out.Name = in.Name
	out.Labels = in.Labels
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata is an autogenerated conversion function.
func Convert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata(in *EmbeddedObjectMetadata, out *v1alpha2.EmbeddedObjectMetadata, s conversion.Scope) error {
	return autoConvert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata(in, out, s)
}

func autoConvert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata(in *v1alpha2.EmbeddedObjectMetadata, out *EmbeddedObjectMetadata, s conversion.Scope) error {
	out.Name = in.Name
	out.Labels = in.Labels
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata is an autogenerated conversion function.
func Convert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata(in *v1alpha2.EmbeddedObjectMetadata, out *EmbeddedObjectMetadata, s conversion.Scope) error {
	return autoConvert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata(in, out, s)
}

func autoConvert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(in *EmbeddedPersistentVolumeClaim, out *v1alpha2.EmbeddedPersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert_v1alpha1_EmbeddedObjectMetadata_To_v1alpha2_EmbeddedObjectMetadata(&in.EmbeddedObjectMetadata, &out.EmbeddedObjectMetadata, s); err != nil {
		return err
	}
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim is an autogenerated conversion function.
func Convert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(in *EmbeddedPersistentVolumeClaim, out *v1alpha2.EmbeddedPersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(in, out, s)
}

func autoConvert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(in *v1alpha2.EmbeddedPersistentVolumeClaim, out *EmbeddedPersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert_v1alpha2_EmbeddedObjectMetadata_To_v1alpha1_EmbeddedObjectMetadata(&in.EmbeddedObjectMetadata, &out.EmbeddedObjectMetadata, s); err != nil {
		return err
	}
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim is an autogenerated conversion function.
func Convert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(in *v1alpha2.EmbeddedPersistentVolumeClaim, out *EmbeddedPersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(in, out, s)
}

func autoConvert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig(in *KokuMetricsConfig, out *v1alpha2.KokuMetricsConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig is an autogenerated conversion function.
func Convert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig(in *KokuMetricsConfig, out *v1alpha2.KokuMetricsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig(in, out, s)
}

func autoConvert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig(in *v1alpha2.KokuMetricsConfig, out *KokuMetricsConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_KokuMetricsConfigSpec_To_v1alpha1_KokuMetricsConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_KokuMetricsConfigStatus_To_v1alpha1_KokuMetricsConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig is an autogenerated conversion function.
func Convert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig(in *v1alpha2.KokuMetricsConfig, out *KokuMetricsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig(in, out, s)
}

func autoConvert_v1alpha1_KokuMetricsConfigList_To_v1alpha2_KokuMetricsConfigList(in *KokuMetricsConfigList, out *v1alpha2.KokuMetricsConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.KokuMetricsConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_KokuMetricsConfig_To_v1alpha2_KokuMetricsConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_KokuMetricsConfigList_To_v1alpha2_KokuMetricsConfigList is an autogenerated conversion function.
func Convert_v1alpha1_KokuMetricsConfigList_To_v1alpha2_KokuMetricsConfigList(in *KokuMetricsConfigList, out *v1alpha2.KokuMetricsConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KokuMetricsConfigList_To_v1alpha2_KokuMetricsConfigList(in, out, s)
}

func autoConvert_v1alpha2_KokuMetricsConfigList_To_v1alpha1_KokuMetricsConfigList(in *v1alpha2.KokuMetricsConfigList, out *KokuMetricsConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KokuMetricsConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_KokuMetricsConfig_To_v1alpha1_KokuMetricsConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_KokuMetricsConfigList_To_v1alpha1_KokuMetricsConfigList is an autogenerated conversion function.
func Convert_v1alpha2_KokuMetricsConfigList_To_v1alpha1_KokuMetricsConfigList(in *v1alpha2.KokuMetricsConfigList, out *KokuMetricsConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha2_KokuMetricsConfigList_To_v1alpha1_KokuMetricsConfigList(in, out, s)
}

func autoConvert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec(in *KokuMetricsConfigSpec, out *v1alpha2.KokuMetricsConfigSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	out.APIURL = in.APIURL
	if err := Convert_v1alpha1_AuthenticationSpec_To_v1alpha2_AuthenticationSpec(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec(&in.Packaging, &out.Packaging, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UploadSpec_To_v1alpha2_UploadSpec(&in.Upload, &out.Upload, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec(&in.PrometheusConfig, &out.PrometheusConfig, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CloudDotRedHatSourceSpec_To_v1alpha2_CloudDotRedHatSourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(v1alpha2.EmbeddedPersistentVolumeClaim)
		if err := Convert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.VolumeClaimTemplate = nil
	}
	return nil
}

// Convert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec(in *KokuMetricsConfigSpec, out *v1alpha2.KokuMetricsConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_KokuMetricsConfigSpec_To_v1alpha2_KokuMetricsConfigSpec(in, out, s)
}

func autoConvert_v1alpha2_KokuMetricsConfigSpec_To_v1alpha1_KokuMetricsConfigSpec(in *v1alpha2.KokuMetricsConfigSpec, out *KokuMetricsConfigSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	out.APIURL = in.APIURL
	if err := Convert_v1alpha2_AuthenticationSpec_To_v1alpha1_AuthenticationSpec(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec(&in.Packaging, &out.Packaging, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec(&in.Upload, &out.Upload, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec(&in.PrometheusConfig, &out.PrometheusConfig, s); err != nil {
		return err
	}
	// WARNING: in.ReportingCycle requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha2_CloudDotRedHatSourceSpec_To_v1alpha1_CloudDotRedHatSourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(EmbeddedPersistentVolumeClaim)
		if err := Convert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.VolumeClaimTemplate = nil
	}
	return nil
}

func autoConvert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus(in *KokuMetricsConfigStatus, out *v1alpha2.KokuMetricsConfigStatus, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	out.APIURL = in.APIURL
	if err := Convert_v1alpha1_AuthenticationStatus_To_v1alpha2_AuthenticationStatus(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus(&in.Packaging, &out.Packaging, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UploadStatus_To_v1alpha2_UploadStatus(&in.Upload, &out.Upload, s); err != nil {
		return err
	}
	out.OperatorCommit = in.OperatorCommit
	if err := Convert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus(&in.Prometheus, &out.Prometheus, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus(&in.Reports, &out.Reports, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CloudDotRedHatSourceStatus_To_v1alpha2_CloudDotRedHatSourceStatus(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus(in *KokuMetricsConfigStatus, out *v1alpha2.KokuMetricsConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_KokuMetricsConfigStatus_To_v1alpha2_KokuMetricsConfigStatus(in, out, s)
}

func autoConvert_v1alpha2_KokuMetricsConfigStatus_To_v1alpha1_KokuMetricsConfigStatus(in *v1alpha2.KokuMetricsConfigStatus, out *KokuMetricsConfigStatus, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	out.APIURL = in.APIURL
	if err := Convert_v1alpha2_AuthenticationStatus_To_v1alpha1_AuthenticationStatus(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus(&in.Packaging, &out.Packaging, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus(&in.Upload, &out.Upload, s); err != nil {
		return err
	}
	out.OperatorCommit = in.OperatorCommit
	if err := Convert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus(&in.Prometheus, &out.Prometheus, s); err != nil {
		return err
	}
	// WARNING: in.ReportingCycle requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus(&in.Reports, &out.Reports, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CloudDotRedHatSourceStatus_To_v1alpha1_CloudDotRedHatSourceStatus(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec(in *PackagingSpec, out *v1alpha2.PackagingSpec, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	return nil
}

// Convert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec(in *PackagingSpec, out *v1alpha2.PackagingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackagingSpec_To_v1alpha2_PackagingSpec(in, out, s)
}

func autoConvert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec(in *v1alpha2.PackagingSpec, out *PackagingSpec, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	return nil
}

// Convert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec is an autogenerated conversion function.
func Convert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec(in *v1alpha2.PackagingSpec, out *PackagingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_PackagingSpec_To_v1alpha1_PackagingSpec(in, out, s)
}

func autoConvert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus(in *PackagingStatus, out *v1alpha2.PackagingStatus, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	out.LastSuccessfulPackagingTime = in.LastSuccessfulPackagingTime
	out.PackagingError = in.PackagingError
	return nil
}

// Convert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus is an autogenerated conversion function.
func Convert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus(in *PackagingStatus, out *v1alpha2.PackagingStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackagingStatus_To_v1alpha2_PackagingStatus(in, out, s)
}

func autoConvert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus(in *v1alpha2.PackagingStatus, out *PackagingStatus, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	out.LastSuccessfulPackagingTime = in.LastSuccessfulPackagingTime
	out.PackagingError = in.PackagingError
	return nil
}

// Convert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus is an autogenerated conversion function.
func Convert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus(in *v1alpha2.PackagingStatus, out *PackagingStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PackagingStatus_To_v1alpha1_PackagingStatus(in, out, s)
}

func autoConvert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec(in *PrometheusSpec, out *v1alpha2.PrometheusSpec, s conversion.Scope) error {
	out.SvcAddress = in.SvcAddress
	out.SkipTLSVerification = in.SkipTLSVerification
	return nil
}

// Convert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec is an autogenerated conversion function.
func Convert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec(in *PrometheusSpec, out *v1alpha2.PrometheusSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PrometheusSpec_To_v1alpha2_PrometheusSpec(in, out, s)
}

func autoConvert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec(in *v1alpha2.PrometheusSpec, out *PrometheusSpec, s conversion.Scope) error {
	out.SvcAddress = in.SvcAddress
	out.SkipTLSVerification = in.SkipTLSVerification
	return nil
}

// Convert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec is an autogenerated conversion function.
func Convert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec(in *v1alpha2.PrometheusSpec, out *PrometheusSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_PrometheusSpec_To_v1alpha1_PrometheusSpec(in, out, s)
}

func autoConvert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus(in *PrometheusStatus, out *v1alpha2.PrometheusStatus, s conversion.Scope) error {
	out.PrometheusConfigured = in.PrometheusConfigured
	out.ConfigError = in.ConfigError
	out.PrometheusConnected = in.PrometheusConnected
	out.ConnectionError = in.ConnectionError
	out.LastQueryStartTime = in.LastQueryStartTime
	out.LastQuerySuccessTime = in.LastQuerySuccessTime
	out.SvcAddress = in.SvcAddress
	out.SkipTLSVerification = in.SkipTLSVerification
	return nil
}

// Convert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus is an autogenerated conversion function.
func Convert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus(in *PrometheusStatus, out *v1alpha2.PrometheusStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PrometheusStatus_To_v1alpha2_PrometheusStatus(in, out, s)
}

func autoConvert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus(in *v1alpha2.PrometheusStatus, out *PrometheusStatus, s conversion.Scope) error {
	out.PrometheusConfigured = in.PrometheusConfigured
	out.ConfigError = in.ConfigError
	out.PrometheusConnected = in.PrometheusConnected
	out.ConnectionError = in.ConnectionError
	out.LastQueryStartTime = in.LastQueryStartTime
	out.LastQuerySuccessTime = in.LastQuerySuccessTime
	out.SvcAddress = in.SvcAddress
	out.SkipTLSVerification = in.SkipTLSVerification
	return nil
}

// Convert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus is an autogenerated conversion function.
func Convert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus(in *v1alpha2.PrometheusStatus, out *PrometheusStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PrometheusStatus_To_v1alpha1_PrometheusStatus(in, out, s)
}

func autoConvert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus(in *ReportsStatus, out *v1alpha2.ReportsStatus, s conversion.Scope) error {
	out.ReportMonth = in.ReportMonth
	out.LastHourQueried = in.LastHourQueried
	out.DataCollected = in.DataCollected
	out.DataCollectionMessage = in.DataCollectionMessage
	return nil
}

// Convert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus(in *ReportsStatus, out *v1alpha2.ReportsStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReportsStatus_To_v1alpha2_ReportsStatus(in, out, s)
}

func autoConvert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus(in *v1alpha2.ReportsStatus, out *ReportsStatus, s conversion.Scope) error {
	out.ReportMonth = in.ReportMonth
	out.LastHourQueried = in.LastHourQueried
	out.DataCollected = in.DataCollected
	out.DataCollectionMessage = in.DataCollectionMessage
	return nil
}

// Convert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus is an autogenerated conversion function.
func Convert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus(in *v1alpha2.ReportsStatus, out *ReportsStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ReportsStatus_To_v1alpha1_ReportsStatus(in, out, s)
}

func autoConvert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus(in *StorageStatus, out *v1alpha2.StorageStatus, s conversion.Scope) error {
	out.VolumeType = in.VolumeType
	out.VolumeMounted = in.VolumeMounted
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(v1alpha2.EmbeddedPersistentVolumeClaim)
		if err := Convert_v1alpha1_EmbeddedPersistentVolumeClaim_To_v1alpha2_EmbeddedPersistentVolumeClaim(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.PersistentVolumeClaim = nil
	}
	return nil
}

// Convert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus is an autogenerated conversion function.
func Convert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus(in *StorageStatus, out *v1alpha2.StorageStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageStatus_To_v1alpha2_StorageStatus(in, out, s)
}

func autoConvert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus(in *v1alpha2.StorageStatus, out *StorageStatus, s conversion.Scope) error {
	out.VolumeType = in.VolumeType
	out.VolumeMounted = in.VolumeMounted
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(EmbeddedPersistentVolumeClaim)
		if err := Convert_v1alpha2_EmbeddedPersistentVolumeClaim_To_v1alpha1_EmbeddedPersistentVolumeClaim(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.PersistentVolumeClaim = nil
	}
	return nil
}

// Convert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus is an autogenerated conversion function.
func Convert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus(in *v1alpha2.StorageStatus, out *StorageStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_StorageStatus_To_v1alpha1_StorageStatus(in, out, s)
}

func autoConvert_v1alpha1_UploadSpec_To_v1alpha2_UploadSpec(in *UploadSpec, out *v1alpha2.UploadSpec, s conversion.Scope) error {
	out.IngressAPIPath = in.IngressAPIPath
	out.UploadWait = in.UploadWait
	// WARNING: in.UploadCycle requires manual conversion: does not exist in peer-type
	out.UploadToggle = in.UploadToggle
	out.ValidateCert = in.ValidateCert
	return nil
}

func autoConvert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec(in *v1alpha2.UploadSpec, out *UploadSpec, s conversion.Scope) error {
	out.IngressAPIPath = in.IngressAPIPath
	out.UploadWait = in.UploadWait
	out.UploadToggle = in.UploadToggle
	out.ValidateCert = in.ValidateCert
	return nil
}

// Convert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec is an autogenerated conversion function.
func Convert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec(in *v1alpha2.UploadSpec, out *UploadSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_UploadSpec_To_v1alpha1_UploadSpec(in, out, s)
}

func autoConvert_v1alpha1_UploadStatus_To_v1alpha2_UploadStatus(in *UploadStatus, out *v1alpha2.UploadStatus, s conversion.Scope) error {
	out.IngressAPIPath = in.IngressAPIPath
	out.UploadToggle = in.UploadToggle
	out.UploadWait = in.UploadWait
	// WARNING: in.UploadCycle requires manual conversion: does not exist in peer-type
	out.UploadError = in.UploadError
	out.LastUploadStatus = in.LastUploadStatus
	out.LastUploadTime = in.LastUploadTime
	out.LastSuccessfulUploadTime = in.LastSuccessfulUploadTime
	out.ValidateCert = in.ValidateCert
	return nil
}

func autoConvert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus(in *v1alpha2.UploadStatus, out *UploadStatus, s conversion.Scope) error {
	out.IngressAPIPath = in.IngressAPIPath
	out.UploadToggle = in.UploadToggle
	out.UploadWait = in.UploadWait
	out.UploadError = in.UploadError
	out.LastUploadStatus = in.LastUploadStatus
	out.LastUploadTime = in.LastUploadTime
	out.LastSuccessfulUploadTime = in.LastSuccessfulUploadTime
	out.ValidateCert = in.ValidateCert
	return nil
}

// Convert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus is an autogenerated conversion function.
func Convert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus(in *v1alpha2.UploadStatus, out *UploadStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_UploadStatus_To_v1alpha1_UploadStatus(in, out, s)
}
