---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-config-role
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
    