name: Build and Publish Images

on:
  push:
    branches:
      - 'main'
    tags:  # run on any tag that starts with `v` but not tags that end with `-downstream`
      - 'v**'
      - '!v**-downstream'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/project-koku/koku-metrics-operator
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=,enable=${{ github.ref_type == 'tag' }}
            # set latest tag for default branch
            type=raw,value=latest
            type=ref,event=branch

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          provenance: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
