name: Build and Push to Quay

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        env:
          TOKEN: ${{ secrets.QUAY_TOKEN }}
        run: |
          docker login --username project-koku+githubreleaseaction --password $TOKEN
          docker build . -t quay.io/project-koku/koku-metrics-operator:$GITHUB_REF
          docker push quay.io/project-koku/koku-metrics-operator:$GITHUB_REF
