name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - downstream
      - main

jobs:
  units:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Display build environment
        run: printenv

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.18' # The Go version to download (if necessary) and use.

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}


      - name: Install kubebuilder
        run : |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz" | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin

      - name: Run tests
        run: |
          make generate manifests
          go test ./... -v -coverprofile cover.out -covermode=atomic

      - name: Upload test coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: cover.out

  coverage:
    name: Coverage
    needs: units
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        # this checkout is required for the coverage report. If we don't do this, then
        # the uploaded report is invalid and codecov doesn't know how to process it.
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Download coverage result from units
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./cover.out
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
